title: Baptiste Lecocq, ingénieur logiciel indépendant à Lille
lang: fr
email: baptiste.lecocq@gmail.com
description: |
  Je m’appelle Baptiste, je suis ingénieur logiciel indépendant sur Lille.
  J'aide les personnes et équipes à définir et répondre à leurs besoins.
  J'y parviens en travaillant pour et avec ces personnes en mettant en place un environnement favorisant les échanges et l'excellence technique.
url: 'https://tiste.io'
tel: +33 6 34 25 45 34
twitter:
  username: tiste
  card: summary
github_username: tiste
social:
  name: Baptiste Lecocq
  links:
    - https://twitter.com/tiste
    - https://www.linkedin.com/in/baptistelecocq
    - https://plus.google.com/+BaptisteLecocq
    - https://github.com/tiste
    - https://keybase.io/tiste
logo: /logo.png
google_analytics: UA-42477577-1

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
