title: Baptiste Lecocq, software engineer in Lille
email: hello@tiste.io
description: >
  Je m’appelle Baptiste, je suis ingénieur d’études et développement sur Lille.
  Je travaille actuellement pour Ineat. Avant cela, j’étais à Londres, chez Codegent.
baseurl: ''
url: 'https://tiste.io'
tel: +33 6 34 25 45 34
mailto: baptiste.lecocq@gmail.com
twitter_username: tiste
github_username: tiste
google_analytics: UA-42477577-1

markdown: kramdown
theme: minima
plugins:
  - jekyll-amp
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
